window.document.onload = function (e) {
  const btnVision = document.querySelector('.vision')
  const btnNext = document.querySelector('.next')
  const btnEng = document.querySelector('.eng')
  const btnRus = document.querySelector('.rus')
  const holdBot = document.querySelector('.hold')
  const verbs = document.querySelector('.verbs')
  const nouns = document.querySelector('.nouns')
  const sentenceTranslate = document.querySelector('.sentence-translate')

  const word = document.querySelector('.current')
  const translate = document.querySelector('.translate')
  const transcriptoion = document.querySelector('.transcriptoion')
  const sentence = document.querySelector('.sentence')
  const visionHold = document.querySelector('.holdWords')
  const holdData = document.querySelector('.holdData')


  let dataRender = []
  function shuffle(array) {
    dataRender=[...array.sort(() => Math.random() - 0.5)]

  }

  // const data = [
  //   { translate: 'enviroment', word: 'окружающая среда' },
  //   { translate: 'wide', word: 'широкий' },
  //   { translate: 'advantages', word: 'приемущества' },
  //   { translate: 'reliable', word: 'надёжный' },
  //   { translate: 'apperance', word: 'внешний вид' },
  //   { translate: 'allay', word: 'сплав' },
  //   { translate: 'compound', word: 'соединение' },
  //   { translate: 'factory', word: 'фабрика' },
  //   { translate: 'near', word: 'близко' },
  //   { translate: 'employees', word: 'работник' },
  //   { translate: 'employeses', word: 'нанимать' },
  //   { translate: 'expensive', word: 'дорогой' },
  //   { translate: 'plenty', word: 'много' },
  //   { translate: 'supple', word: 'поставка' },
  //   { translate: 'advert', word: 'реклама' },
  //   { translate: 'manufactur', word: 'производство' },
  //   { translate: 'negotiations', word: 'переговоры' },
  //   { translate: 'suggestions', word: 'предложения' },
  //   { translate: 'seem', word: 'кажется' },
  //   { translate: 'during', word: 'в течении (времени)' },
  //   { translate: 'equipment', word: 'оборудование' },
  //   { translate: 'abviously', word: 'очевидно' },
  //   { translate: 'opportunities', word: 'возможности' },
  //   { translate: 'probably', word: 'возможно' },
  //   { translate: 'growing', word: 'растущий' },
  //   { translate: 'however', word: 'однако' },
  //   { translate: 'often', word: 'часто' },
  //   { translate: 'perhaps', word: 'возможно' },
  //   { translate: 'consumer', word: 'потребитель' },
  //   { translate: 'wish', word: 'желание' },
  //   { translate: 'definition', word: 'определение' },
  //   { translate: 'reduce', word: 'уменьшить' },
  //   { translate: 'almost', word: 'почти' },
  //   { translate: 'nap', word: 'вздремнуть' },
  //   { translate: 'evidence', word: 'доказательства' },
  //   { translate: 'fault', word: 'ошибка' },
  //   { translate: 'judje', word: 'судья' },
  //   { translate: 'half', word: 'половина' },
  //   { translate: 'above', word: 'сверху' },
  //   { translate: 'suggest', word: 'предлогать' },
  //   { translate: 'early', word: 'рано' },
  //   { translate: 'otherwise', word: 'иначе (думаю)' },
  //   { translate: 'prefer', word: 'предпочитать' },
  //   { translate: 'both', word: 'оба' },
  //   { translate: 'improve', word: 'улачшать' },
  //   { translate: 'explain', word: 'объяснять' },
  //   { translate: 'topic', word: 'рассказ' },
  //   { translate: 'cheap', word: 'дешёвый' },
  //   { translate: 'below', word: 'ниже' },
  //   { translate: 'gestures', word: 'жесты' },
  //   { translate: 'nervouse', word: 'нервный' },
  //   { translate: 'summarise', word: 'итог' },
  //   { translate: 'intorduce', word: 'вводить' },
  //   { translate: 'to sum up', word: 'подытожить' },
  //   { translate: 'conclusion', word: 'заключение' },
  //   { translate: 'pronunciation', word: 'произношение' },
  //   { translate: 'prepare', word: 'подготовить' },
  //   { translate: 'rest', word: 'остальное' },
  //   { translate: 'involved', word: 'вовлеченный' },
  //   { translate: 'justice', word: 'справедливость' },
  //   { translate: 'entertament', word: 'развлечения' },
  //   { translate: 'civil servants', word: 'гос. служащий' },
  //   { translate: 'spokesperson', word: 'секретарь' },
  //   { translate: 'responsibility', word: 'ответственность, обязаность' },
  //   { translate: 'daily', word: 'каждый день' },
  //   { translate: 'spend', word: 'тратить' },
  //   { translate: 'emergency', word: 'срочно, непредвиденная ситуация' },
  //   { translate: 'disaster', word: 'катастроф' },
  //   { translate: 'desire', word: 'желание' },
  //   { translate: 'intention', word: 'намерения' },
  //   { translate: 'gift', word: 'подарок' },
  //   { translate: 'become', word: 'становиться' },
  //   { translate: 'according', word: 'согластно (иследованию)' },
  //   { translate: 'arrive', word: 'прибывать' },
  //   { translate: 'beside', word: 'рядом' },
  //   { translate: 'meantime', word: 'промежуток (времни), тем времнем' },
  //   { translate: 'blame', word: 'обвинять' },
  //   { translate: 'audience', word: 'аудитория' },
  //   { translate: 'joke', word: 'шутка' },
  //   { translate: 'vocabulary', word: 'запас слов' },
  //   { translate: 'adverts', word: 'отношение' },
  //   { translate: 'adverts', word: 'портативный' },
  //   { translate: 'портативный', word: 'ошибка' },
  //   { translate: 'available', word: 'доступный, в наличии' },
  //   { translate: 'launched', word: 'запускать' },
  //   { translate: 'quite', word: 'довольно, действительно' },
  //   { translate: 'rarely', word: "редко" },
  //   { translate: 'journey', word: 'путешествие' },
  //   { transalate: "excited", word: "взыолнованный" },
  //   { transalate: "frequently", word: "часто" },
  //   { transalate: "conversation", word: "беседа" },
  //   { transalate: "suffer", word: "страдать" },
  //   { translate: 'able', word: 'способный' },
  //   { translate: 'relationship', word: 'отношения (взаимосвязь)' },
  //   { translate: 'particular', word: 'определенный, конкретный' },
  //   { translate: 'weak', word: 'слабый' },
  //   { translate: 'efficient', word: 'эффективный' },
  //   { translate: 'venue', word: 'место встречи, место сбора' },
  //   { translate: 'facilities', word: 'оборудование,приспособления' },
  //   { translate: 'instance', word: 'пример (example)' },
  //   { translate: 'embarrassed', word: 'смущенный' },
  //   { translate: 'abroad', word: 'за границей' },
  //   { translate: 'apply', word: 'применять,использоват' },
  //   { translate: 'degree', word: 'степень, уровень' },
  //   { translate: 'guess', word: 'догадываться' },
  //   { translate: 'knowledge', word: 'знания' },
  //   { translate: 'accommodation', word: 'размещение,жилье' },
  //   { translate: 'mild', word: 'мягкий' },
  //   { translate: 'accommodation', word: 'влажный' },
  //   { translate: 'against', word: 'против' },
  //   { translate: 'several', word: 'несколько' },
  //   { translate: 'drought', word: 'засуха' },
  //   { translate: 'flood', word: 'наводнение' },
  //   { translate: 'bloom', word: 'цветение' },
  //   { translate: 'wheat', word: 'пшеница' },
  //   { translate: 'grain', word: 'зерно' },
  //   { translate: 'cause', word: 'причина' },
  //   { translate: 'lack', word: 'отсутствие' },
  //   { translate: 'shortage', word: 'нехватка' },
  //   { translate: 'consequences', word: 'последствия' },
  //   { translate: 'pollution', word: 'загрязнение' },
  //   { translate: 'exact', word: 'точный' },
  //   { translate: 'jar', word: 'банка (как варенье)' },
  //   { translate: 'pot', word: 'стаканчик (как йогурт)' },
  //   { translate: 'waste', word: 'отходы' },
  //   { translate: 'government', word: 'правительство' },
  //   { translate: 'rubbish', word: 'мусор' },
  //   { translate: 'untidy', word: 'неопрятный' },
  //   { translate: 'funding', word: 'финансирование' },
  //   { translate: 'proposal', word: 'предложение,заявка' },
  //   { translate: 'benefits', word: 'выгода' },
  //   { translate: 'annual', word: 'ежегодный' },
  //   { translate: 'evaluate', word: 'оценивать' },
  //   { translate: 'persuade', word: 'убеждать' },
  //   { translate: 'dedicated', word: 'посвященный' },
  //   { translate: 'suddenly', word: 'внезапно' },
  //   { translate: 'steadily', word: 'непрерывно' },
  //   { translate: 'significant', word: 'существенный' },
  //   { translate: 'aim', word: 'цель,задачa' },
  //   { translate: 'shaving', word: 'бритье' },
  //   { translate: 'despite', word: 'несмотря на' },
  //   { translate: 'competition', word: 'соревнование' },
  //   { translate: 'advice', word: 'совет' },
  //   { translate: 'turgently', word: 'срочно' },
  //   { translate: 'confidence', word: 'уверенность' },
  //   { translate: 'regard', word: 'уважение' },
  //   { translate: 'regret', word: 'сожаление' },
  //   { translate: 'generous', word: 'щедрый' },
  //   { translate: 'regard to', word: 'в отношении чего либо' },
  //   { translate: 'patient', word: 'терпеливый' },
  //   { translate: 'wise', word: 'мудрый' },
  //   { translate: 'jolly', word: 'веселый' },
  //   { translate: 'handsome', word: 'beautifull для мужчины' },
  //   { translate: 'bossy', word: 'властный' },
  //   { translate: 'moody', word: 'угрюмый' },
  //   { translate: 'sensitive', word: 'чувствительный' },
  //   { translate: 'thoughtful', word: 'заботливый, внимательный' },
  //   { translate: 'divide', word: 'делить' },
  //   { translate: 'reserved', word: 'скрытный, замкнутый' },
  //   { translate: 'measure', word: 'мера, степень' },
  // ]

  // const data =[
  //   { translate: 'Быть, являться', word: 'Ser', transcriptoion:'сер', sentenceTranslate:'La documentación y las placas pueden SER falsas.',sentense:'Значки могут БЫТЬ подделаны.' },
  //   { translate: 'Сказать, говорить', word: 'Decir', transcriptoion:'десир', sentenceTranslate:'¿Me quieres DESIR algo, Scofield?',sentense:'Хочешь что-то СКАЗАТЬ, Скофилд?' },
  //   { translate: 'Говорить', word: 'Hablar', transcriptoion:'Аблар', sentenceTranslate:'Ahora, matasanos, HABLAR o el muchacho muere.',sentense:'Теперь костоправ, ГОВОРИ или этот молодой парень умрет.' },
  //   { translate: 'быть, находиться', word: 'Estar', transcriptoion:'эстар', sentenceTranslate:'No podía ESTAR en Medisonus al mismo tiempo.',sentense:'И он не мог БЫТЬ в это же время в Медисонусе.' },
  //   { translate: 'писать', word: 'Escribir', transcriptoion:'Эскрибир', sentenceTranslate:'A leer y a ESCRIBIR..',sentense:'Читать и  ПИСАТЬ' },
  //   { translate: 'Идти, ехать', word: 'Leer', transcriptoion:'Леэр', sentenceTranslate:'Puede LEER a las personas.',sentense:'Ты можешь ЧИТАТЬ людей.' },
  //   { translate: 'Идти, ехать', word: 'Leer', transcriptoion:'Ир', sentenceTranslate:'Vale, ¿puedes IR a ayudar a la señorita Lauren, vale?',sentense:'ИДИ, помоги мисс Лорен, ладно?' },
  //   { translate: 'Идти, ехать', word: 'Leer', transcriptoion:'Ир', sentenceTranslate:'Vale, ¿puedes IR a ayudar a la señorita Lauren, vale?',sentense:'ИДИ, помоги мисс Лорен, ладно?' },
  //
  // ]

  const data =[
    { word: 'Ser'},
    {  word: 'Decir' },
    { word: 'Hablar' },
    {  word: 'Estar' },
    { word: 'Escribir'  },
    { word: 'Leer'},
    { word: 'Ir'},
    { word: 'Tomar'},
    { word: 'Comer'},
    { word: 'Viver'},
    { word: 'Ver'},
    { word: 'Mirar'},
    { word: 'Oir'},
    { word: 'Escuchar'},
    { word: 'Liamar'},
    { word: 'Poner'},
    { word: 'Sacar'},
    { word: 'Entrar'},
    { word: 'Salir'},
    { word: 'Subir'},
    { word: 'Bajar'},
    { word: 'Pensar'},
    { word: 'Perder'},
    { word: 'Esperar'},
    { word: 'Lievar'},
    { word: 'Volver'},
    { word: 'Usar'},
    { word: 'Trabajar'},
    { word: 'Empezar'},
    { word: 'Terminar'},
    { word: 'Tener'},
    { word: 'Saber'},
    { word: 'Conocer'},
    { word: 'Abrir'},
    { word: 'Cerrar'},
    { word: 'Aceptar'},
    { word: 'Rechazar'},
    { word: 'Ayudar'},
    { word: 'Cambiar'},
    { word: 'Buscar'},
    { word: 'Encontrar'},
    { word: 'Caer'},
    { word: 'Bailar'},
    { word: 'Contar'},
    { word: 'Correr'},
    { word: 'Comprender'},
    { word: 'Querer'},
    { word: 'Deber'},
    { word: 'Dejar'},
    { word: 'Comprar'},
    { word: 'Existir'},
    { word: 'Gustar'},
    { word: 'Hacer'},
    { word: 'Nacer'},
    { word: 'Morir'},
    { word: 'Necesitar'},
    { word: 'Mentir'},
    { word: 'Preparar'},
    { word: 'Beber'},
    { word: 'Estudiar'},
    { word: 'Vender'},
    { word: 'Ganar'},
    { word: 'Poder'},
    { word: 'Dar'},
    { word: 'Recibir'},
    { word: 'Quedar'},
    { word: 'Recordar'},
    { word: 'Realizar'},
    { word: 'Sentir'},
    { word: 'Suponer'},
    { word: 'Dormir'},
    { word: 'Intentar'},
    { word: 'Mantener'},
    ]
  // const data = [
  //   { translate: 'enviroment', word: 'окружающая среда' },
  //   { translate: 'wide', word: 'широкий' },
  //   { translate: 'advantages', word: 'приемущества' },
  //   { translate: 'reliable', word: 'надёжный' },
  //   { translate: 'apperance', word: 'внешний вид' },
  //   { translate: 'allay', word: 'сплав' },
  //   { translate: 'compound', word: 'соединение' },
  //   { translate: 'factory', word: 'фабрика' },
  //   { translate: 'near', word: 'близко' },
  //   { translate: 'employees', word: 'работник' },
  //   { translate: 'employeses', word: 'нанимать' },
  //   { translate: 'expensive', word: 'дорогой' },
  //   { translate: 'plenty', word: 'много' },
  //   { translate: 'supple', word: 'поставка' },
  //   { translate: 'advert', word: 'реклама' },
  //   { translate: 'manufactur', word: 'производство' },
  //   { translate: 'negotiations', word: 'переговоры' },
  //   { translate: 'suggestions', word: 'предложения' },
  //   { translate: 'seem', word: 'кажется' },
  //   { translate: 'during', word: 'в течении (времени)' },
  //   { translate: 'equipment', word: 'оборудование' },
  //   { translate: 'abviously', word: 'очевидно' },
  //   { translate: 'opportunities', word: 'возможности' },
  //   { translate: 'probably', word: 'возможно' },
  //   { translate: 'growing', word: 'растущий' },
  //   { translate: 'however', word: 'однако' },
  //   { translate: 'often', word: 'часто' },
  //   { translate: 'perhaps', word: 'возможно' },
  //   { translate: 'consumer', word: 'потребитель' },
  //   { translate: 'wish', word: 'желание' },
  //   { translate: 'definition', word: 'определение' },
  //   { translate: 'reduce', word: 'уменьшить' },
  //   { translate: 'almost', word: 'почти' },
  //   { translate: 'nap', word: 'вздремнуть' },
  //   { translate: 'evidence', word: 'доказательства' },
  //   { translate: 'fault', word: 'ошибка' },
  //   { translate: 'judje', word: 'судья' },
  //   { translate: 'half', word: 'половина' },
  //   { translate: 'above', word: 'сверху' },
  //   { translate: 'suggest', word: 'предлогать' },
  //   { translate: 'early', word: 'рано' },
  //   { translate: 'otherwise', word: 'иначе (думаю)' },
  //   { translate: 'prefer', word: 'предпочитать' },
  //   { translate: 'both', word: 'оба' },
  //   { translate: 'improve', word: 'улачшать' },
  //   { translate: 'explain', word: 'объяснять' },
  //   { translate: 'topic', word: 'рассказ' },
  //   { translate: 'cheap', word: 'дешёвый' },
  //   { translate: 'below', word: 'ниже' },
  //   { translate: 'gestures', word: 'жесты' },
  //   { translate: 'nervouse', word: 'нервный' },
  //   { translate: 'summarise', word: 'итог' },
  //   { translate: 'intorduce', word: 'вводить' },
  //   { translate: 'to sum up', word: 'подытожить' },
  //   { translate: 'conclusion', word: 'заключение' },
  //   { translate: 'pronunciation', word: 'произношение' },
  //   { translate: 'prepare', word: 'подготовить' },
  //   { translate: 'rest', word: 'остальное' },
  //   { translate: 'involved', word: 'вовлеченный' },
  //   { translate: 'justice', word: 'справедливость' },
  //   { translate: 'entertament', word: 'развлечения' },
  //   { translate: 'civil servants', word: 'гос. служащий' },
  //   { translate: 'spokesperson', word: 'секретарь' },
  //   { translate: 'responsibility', word: 'ответственность, обязаность' },
  //   { translate: 'daily', word: 'каждый день' },
  //   { translate: 'spend', word: 'тратить' },
  //   { translate: 'emergency', word: 'срочно, непредвиденная ситуация' },
  //   { translate: 'disaster', word: 'катастроф' },
  //   { translate: 'desire', word: 'желание' },
  //   { translate: 'intention', word: 'намерения' },
  //   { translate: 'gift', word: 'подарок' },
  //   { translate: 'become', word: 'становиться' },
  //   { translate: 'according', word: 'согластно (иследованию)' },
  //   { translate: 'arrive', word: 'прибывать' },
  //   { translate: 'beside', word: 'рядом' },
  //   { translate: 'meantime', word: 'промежуток (времни), тем времнем' },
  //   { translate: 'blame', word: 'обвинять' },
  //   { translate: 'audience', word: 'аудитория' },
  //   { translate: 'joke', word: 'шутка' },
  //   { translate: 'vocabulary', word: 'запас слов' },
  //   { translate: 'adverts', word: 'отношение' },
  //   { translate: 'adverts', word: 'портативный' },
  //   { translate: 'портативный', word: 'ошибка' },
  //   { translate: 'available', word: 'доступный, в наличии' },
  //   { translate: 'launched', word: 'запускать' },
  //   { translate: 'quite', word: 'довольно, действительно' },
  //   { translate: 'rarely', word: "редко" },
  //   { translate: 'journey', word: 'путешествие' },
  //   { transalate: "excited", word: "взыолнованный" },
  //   { transalate: "frequently", word: "часто" },
  //   { transalate: "conversation", word: "беседа" },
  //   { transalate: "suffer", word: "страдать" },
  //   { translate: 'able', word: 'способный' },
  //   { translate: 'relationship', word: 'отношения (взаимосвязь)' },
  //   { translate: 'particular', word: 'определенный, конкретный' },
  //   { translate: 'weak', word: 'слабый' },
  //   { translate: 'efficient', word: 'эффективный' },
  //   { translate: 'venue', word: 'место встречи, место сбора' },
  //   { translate: 'facilities', word: 'оборудование,приспособления' },
  //   { translate: 'instance', word: 'пример (example)' },
  //   { translate: 'embarrassed', word: 'смущенный' },
  //   { translate: 'abroad', word: 'за границей' },
  //   { translate: 'apply', word: 'применять,использоват' },
  //   { translate: 'degree', word: 'степень, уровень' },
  //   { translate: 'guess', word: 'догадываться' },
  //   { translate: 'knowledge', word: 'знания' },
  //   { translate: 'accommodation', word: 'размещение,жилье' },
  //   { translate: 'mild', word: 'мягкий' },
  //   { translate: 'accommodation', word: 'влажный' },
  //   { translate: 'against', word: 'против' },
  //   { translate: 'several', word: 'несколько' },
  //   { translate: 'drought', word: 'засуха' },
  //   { translate: 'flood', word: 'наводнение' },
  //   { translate: 'bloom', word: 'цветение' },
  //   { translate: 'wheat', word: 'пшеница' },
  //   { translate: 'grain', word: 'зерно' },
  //   { translate: 'cause', word: 'причина' },
  //   { translate: 'lack', word: 'отсутствие' },
  //   { translate: 'shortage', word: 'нехватка' },
  //   { translate: 'consequences', word: 'последствия' },
  //   { translate: 'pollution', word: 'загрязнение' },
  //   { translate: 'exact', word: 'точный' },
  //   { translate: 'jar', word: 'банка (как варенье)' },
  //   { translate: 'pot', word: 'стаканчик (как йогурт)' },
  //   { translate: 'waste', word: 'отходы' },
  //   { translate: 'government', word: 'правительство' },
  //   { translate: 'rubbish', word: 'мусор' },
  //   { translate: 'untidy', word: 'неопрятный' },
  //   { translate: 'funding', word: 'финансирование' },
  //   { translate: 'proposal', word: 'предложение,заявка' },
  //   { translate: 'benefits', word: 'выгода' },
  //   { translate: 'annual', word: 'ежегодный' },
  //   { translate: 'evaluate', word: 'оценивать' },
  //   { translate: 'persuade', word: 'убеждать' },
  //   { translate: 'dedicated', word: 'посвященный' },
  //   { translate: 'suddenly', word: 'внезапно' },
  //   { translate: 'steadily', word: 'непрерывно' },
  //   { translate: 'significant', word: 'существенный' },
  //   { translate: 'aim', word: 'цель,задачa' },
  //   { translate: 'shaving', word: 'бритье' },
  //   { translate: 'despite', word: 'несмотря на' },
  //   { translate: 'competition', word: 'соревнование' },
  //   { translate: 'advice', word: 'совет' },
  //   { translate: 'turgently', word: 'срочно' },
  //   { translate: 'confidence', word: 'уверенность' },
  //   { translate: 'regard', word: 'уважение' },
  //   { translate: 'regret', word: 'сожаление' },
  //   { translate: 'generous', word: 'щедрый' },
  //   { translate: 'regard to', word: 'в отношении чего либо' },
  //   { translate: 'patient', word: 'терпеливый' },
  //   { translate: 'wise', word: 'мудрый' },
  //   { translate: 'jolly', word: 'веселый' },
  //   { translate: 'handsome', word: 'beautifull для мужчины' },
  //   { translate: 'bossy', word: 'властный' },
  //   { translate: 'moody', word: 'угрюмый' },
  //   { translate: 'sensitive', word: 'чувствительный' },
  //   { translate: 'thoughtful', word: 'заботливый, внимательный' },
  //   { translate: 'divide', word: 'делить' },
  //   { translate: 'reserved', word: 'скрытный, замкнутый' },
  //   { translate: 'measure', word: 'мера, степень' },
  //
  // ]


  const dataVerbs =[
    {word:'Hola'},
    {word:'¡Buenos días!'},
    {word:'¡Buenos tardes!'},
    {word:'¿Que tal?'},
    {word:'¿Cómo está usted?'},
    {word:'Muy bien, gracias'},
    {word:'Por favor'},
    {word:'Gracias'},
    {word:'Vale'},
    {word:'¡Hasta luego!'},
    {word:'¡Hasta pronto!'},
    {word:'¡Hasta la vista!'},
    {word:'Nos vemos'},
    {word:'¿Como te llamas?'},
    {word:'¿Como se llama usted?'},
    {word:'Me llamo'},
    {word:'Mucho gusto'},
    {word:'¿De donde eres?'},
    {word:'¿De dónde es usted?'},
    {word:'Soy de Russia'},
    {word:'¿Cuantos años tienes?'},
    {word:'¿Cuantos años tienes usted?'},
    {word:'Tengo...anos'},
  ]
  let i = 0

  let shaffleData =(theme)=> {
    return shuffle(theme)
  }

  verbs.addEventListener('click',()=>{
    shaffleData(dataVerbs)
  })
  nouns.addEventListener('click',()=>{
    shaffleData(data)
  })


let lang
const holdWords = []

// btnEng.addEventListener('click',()=>lang='eng')
// btnRus.addEventListener('click',()=>lang='rus')
  function replaceAll(str, find, replace) {
    return str.replace(new RegExp(find, 'g'), replace);
  }
  btnNext.addEventListener('click', () => {
    const words = dataRender[i]
    if(lang==='eng'||lang===undefined){
      let req = replaceAll(words.word,' ','%20')
      req = replaceAll(req, ',','')
      word.innerHTML = words.word
      // translate.innerHTML = words.translate
      btnVision.href = `https://translate.google.ru/?hl=ru&tab=wT&sl=es&tl=ru&text=${req}&op=translate`
      // translate.classList.add('hide')
      // transcriptoion.innerHTML = words.transcriptoion
      // sentenceTranslate.innerHTML = words.sentenceTranslate
      // sentence.innerHTML = words.sentense
      // sentence.classList.add('hide')
      // sentence.classList.add('hide').classList.add('hide')
    i++}
    // else {
    //   word.innerHTML = words.translate
    //   translate.innerHTML = words.word
    //   translate.classList.add('hide')
    //   i++
    // }
  })
  // btnVision.addEventListener('click', () => {
  //   translate.classList.remove('hide')
  //   sentence.classList.remove('hide')
  //   sentence.classList.remove('hide')
  // })

  holdBot.addEventListener('click',()=>holdWords.push(dataRender[i-1]))
  visionHold.addEventListener('click',()=>{
    for(let j=0; j<holdWords.length; j++){
      holdData.innerHTML += `
      <div>
      ${holdWords[j].word}
<!--       : ${holdWords[j].translate
      }-->
      </div>`
    }
  })
}

window.document.onload()